README.md, integration-test/oauth-tooling/getAccessToken.spec.ts, package.json, src/oauth-tooling.ts
=> fix(scopes-parameter): call split() on scopes parameter

.gitignore, README.md, package.json, tsconfig.json
=> chore(project): publish to npm

package.json
=> chore(project): fix publish script

package.json, src/TokenCache.ts, src/utils.ts, tslint.json
=> chore(project): fix linting

package.json
=> chore(project): publishConfig in package.json

package.json, src/typings/btoa.d.ts, src/typings/form-urlencoded.d.ts, src/typings/node-fetch.d.ts, tsconfig.json
=> chore(typings): get rid of zalando dependencies

.gitignore, package.json, src/express-tooling.ts, src/oauth-tooling.ts, src/typings/btoa.d.ts, src/typings/form-urlencoded.d.ts, test/unit/express-tooling.ts, tsconfig.json
=> 43 refactor package json

integration-test/mock-tooling/index.ts, integration-test/oauth-tooling/getAccessToken.spec.ts, integration-test/oauth-tooling/getTokenInfo.spec.ts, integration-test/oauth-tooling/tokenCache.spec.ts, package.json, src/TokenCache.ts, src/express-tooling.ts, src/mock-tooling/index.ts, src/oauth-tooling.ts, src/types/BodyParameters.ts, src/types/MiddlewareOptions.ts, src/types/MockOptions.ts, src/types/OAuthConfig.ts, src/types/Token.ts, src/types/TokenInfo.ts, src/utils.ts
=> 48 export of types

package.json, src/types/Token.ts, src/types/TokenInfo.ts, src/utils.ts
=> feat(cleanup): remove cn

package.json, src/express-tooling.ts, src/index.ts, src/types/ExtendedRequest.ts, src/types/Logger.ts, src/types/Precedence.ts, src/types/index.ts, test/unit/express-tooling.ts, tsconfig.json
- add types
- minor improvements
```
---------------------|----------|----------|----------|----------|----------------|
File                 |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
---------------------|----------|----------|----------|----------|----------------|
All files            |     97.1 |    92.86 |    94.55 |    97.55 |                |
src                 |    96.69 |    93.24 |    93.75 |    97.19 |                |
TokenCache.ts      |    92.68 |      100 |    83.33 |    94.87 |          60,62 |
constants.ts       |      100 |      100 |      100 |      100 |                |
express-tooling.ts |    94.74 |    85.71 |      100 |    94.59 |          52,89 |
oauth-tooling.ts   |    98.18 |    92.86 |      100 |    98.18 |            225 |
utils.ts …
```
=> refactor(express-tooling): clean

LICENSE
=> docs(license): change layout

package.json
=> feat(tslint): Upgrade dependencies

README.md
=> chore(readme): add npm stats

.travis.yml, README.md, package.json
=> feat(codecoverage): added code-coverage

README.md, package.json
=> fix(codecoverage): Fix code coverage

CODE_OF_CONDUCT.md, CONTRIBUTING.md
=> 66 meta info files

CONTRIBUTING.md, README.md, integration-test/data/credentials/client.json, integration-test/data/credentials/user.json, integration-test/mock-tooling/index.ts, integration-test/oauth-tooling/getAccessToken.spec.ts, integration-test/oauth-tooling/middlewares.spec.ts, integration-test/oauth-tooling/tokenCache.spec.ts, package.json, src/utils.ts, test/unit/credentials/client.json, test/unit/credentials/user.json, test/unit/express-tooling.ts, test/unit/utils.ts
=> 85 cleanup

README.md, package.json
=> chore(project): renaming

CONTRIBUTING.md, README.md, package.json
=> chore(cleanup): Rename to authmosphere

package.json, src/express-tooling.ts, src/mock-tooling/index.ts, src/oauth-tooling.ts, src/utils.ts
=> feat(add types): added types

README.md, package.json, src/express-tooling.ts, src/oauth-tooling.ts, test/unit/index.ts
- add migration information to README
close #91
=> feat(tooling): update function signatures

README.md, src/types/Token.ts, tsconfig.json
See [87](https://github.com/zalando-incubator/lib-oauth-tooling/issues/87)
For indexer type to describe the shape of the object in more detail
=> chore(token.ts): Add type declaration

README.md, integration-test/oauth-tooling/tokenCache.spec.ts, src/TokenCache.ts, src/types/OAuthConfig.ts, src/types/TokenCacheConfig.ts, src/types/index.ts
=> feat(tokenCacheConfig): provide config for cache

Security.md
As part of our Rules of Play this one is mandatory, so I just wanted to add it 😄
=> docs(general): Adding Security.md

package.json
=> chore(version): set to 1.0.0

README.md, integration-test/oauth-tooling/getAccessToken.spec.ts, integration-test/oauth-tooling/getTokenInfo.spec.ts, package.json, src/constants.ts, src/oauth-tooling.ts
Furthermore, tests are now using nock instead of explicitly starting a server.
close #104 
close #15
=> Support Client Crendetials Grant

package.json
=> chore(version): bump

.nycrc, package-lock.json, package.json
=> refactor(nyc): Swap config from package.json

CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
=> docs(contributing): Update and templates

CONTRIBUTING.md, ISSUE_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
=> docs(templates): Update templates

CHANGELOG.md, MIGRATION_GUIDE.md, README.md, package.json
=> 131 changelog

integration-test/oauth-tooling/getAccessToken.spec.ts, test/unit/mock-tooling.ts
=> test(getAccessToken): add test for error handling

README.md, package.json, src/express-tooling.ts, test/unit/express-tooling.ts, tslint.json
=> Refactoring + Test Fix

integration-test/oauth-tooling/getAccessToken.spec.ts, src/oauth-tooling.ts, src/types/OAuthConfig.ts
=> feat(getAccessToken): accept optional body params

package.json, src/index.ts
=> fix(types): export missing types

src/safe-logger.ts, test/unit/safe-logger.ts
=> fix(safe-logger): bind this

integration-test/oauth-tooling/tokenCache.spec.ts, src/index.ts, src/token-cache.ts, src/types/TokenCacheConfig.ts
=> feat(token-cache): optional logger

MIGRATION_GUIDE.md, src/express-tooling.ts
=> add initial migration guide

package-lock.json, package.json, src/oauth-tooling.ts
=> feat(type): make getTokenInfo generic

package-lock.json, package.json
=> 159 prepare new package

package-lock.json, package.json
=> fix(deps): Update unsecure dependency

package-lock.json, package.json, src/typings/btoa.d.ts, src/utils.ts
=> refactor(btoa): add own implementation and get rid of dep

CHANGELOG.md, MIGRATION_GUIDE.md, README.md
=> docs(migration): migration guide

CHANGELOG.md, MIGRATION_GUIDE.md, package-lock.json, package.json, src/oauth-tooling.ts, src/types/OAuthConfig.ts, src/utils.ts
=> feature(oauth-config): use less specific type

integration-test/oauth-tooling/tokenCache.spec.ts, package.json, src/token-cache.ts
=> 173 token cache key handling

API.md, CHANGELOG.md, README.md, integration-test/mock-tooling/index.ts, package-lock.json, package.json, src/mock-tooling/index.ts, src/types/MockOptions.ts
=> add documentation for mock tooling

API.md, CHANGELOG.md, src/oauth-tooling.ts
=> docs(api-doc): oauth tooling api docs

API.md, README.md, src/express-tooling.ts
=> 174 doc express tooling

API.md, src/oauth-tooling.ts
=> docs(jsdoc): update jsdoc for oauth tooling

integration-test/mock-tooling/index.ts, package-lock.json, src/mock-tooling/index.ts
=> fix(lint): tooling

CHANGELOG.md, README.md, package-lock.json, package.json
=> docs(review): some minor fixes

API.md, CHANGELOG.md
=> docs(review): minor typos in docs

Security.md
=> docs(security): Update security.md

README.md, package-lock.json, package.json
=> feat(code analysis): Added nsp, codacy badge and updated deps

package-lock.json, package.json
=> fix(nyc): Downgraded dependency

package.json
=> feat(verbosity): add verbosity flag for coveralls

CONTRIBUTING.md
=> docs(security): Link security from contribution

package-lock.json, package.json
=> fix(hoek): Added hoek as dependency to fix vulnerability

API.md, integration-test/oauth-tooling/getAccessToken.spec.ts, package-lock.json, package.json
=> 216 security

package-lock.json, package.json, src/express-tooling.ts
close #211 
Also bumping version to 2.0.6 (patch).
=> fix(express-tooling): pass logger to getTokenInfo and log error

src/index.ts
=> fix(type): Export GetTokenInfo from index.ts

.nycrc, package-lock.json, package.json
=> chore(dependencies): fix vulnerabilities

Security.md
=> docs(security.md): update content

CHANGELOG.md, package.json, src/utils.ts
=> fix(lint): Fix linting errors

package-lock.json, package.json, src/safe-logger.ts, test/unit/safe-logger.ts
=> fix(287): log4js error - this.log is not a function
